//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rehabilitation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        [Display(Name = "Tên đăng nhập")]
        public string Username { get; set; }
        [Display(Name = "Mật khẩu")]
        public string Password { get; set; }
        [Display(Name = "Loại tài khoản")]
        public string Role { get; set; }
        [Display(Name = "Khởi tạo")]
        public System.DateTime Created { get; set; }
        [Display(Name = "Chỉnh sửa gần nhất")]
        public System.DateTime LastModified { get; set; }
        public string NewPassword { get; set; }
        [Compare("NewPassword", ErrorMessage = "Xác nhận mật khẩu không trùng khớp")]
        public string ConfirmPassowrd { get; set; }
    }
}
